#!/bin/sh

PREFIX="/usr/local/"

set -e

echo "Checking system..."

# Validate
if [ "$(uname)" != "Darwin" ]; then
  echo "\nERROR: CodeSync only works on Mac OS X platforms."
  exit 1
fi
if [ "$(which ruby)" == "" ]; then
  echo "\nERROR: CodeSync requires ruby: http://www.ruby-lang.org/en/"
  exit 1
fi
if [ "$(ruby -e "print require 'osx/foundation'" 2>/dev/null)" != "true" ]; then
  echo "\nERROR: CodeSync requires RubyCocoa: http://rubycocoa.sourceforge.net/" 
  echo " + INSTALL the correct version for your system: http://sourceforge.net/projects/rubycocoa/files/"
  exit 1
fi

LIB_DIR=$(ruby -e 'print $:.first')
echo $LIB_DIR
if [[ "$LIB_DIR" == "nil" || "$LIB_DIR" == "" ]]; then
  echo "ERROR: Could not determine Ruby's library directory. Reinstall Ruby and try again. http://www.ruby-lang.org/en/"
  exit 1
fi

echo "Done\n"

echo "Installing..."

# Copy files
cp -rv lib/* $LIB_DIR
if [ $? -ne 0 ]; then
  echo "\nInstall Failed"
  exit 1
fi

cp -v bin/codeSync $INSTALL_DIR/bin
if [ $? -ne 0 ]; then
  echo "\nInstall Failed"
  exit 1
fi

chmod 755 $INSTALL_DIR/bin/codeSync
if [ $? -ne 0 ]; then
  echo "\nInstall Failed"
  exit 1
fi


# Done
echo "\nInstall Complete"